### ISSUE TITLE
Application not working

### ISSUE THREAD

**Issue by ccc-developer** [bengm/wordler#1]
Steps to recreate:

1.) Enter "green" letters "i," in the 3rd position, "e" in the 5th position.
2.) Click, "Find Matches" Letter Frequency calculates, no words appear in "Possible Matches" list, nor any in "Guess Suggestions"

![wordler](https://user-images.githubusercontent.com/45178131/149781914-8302fd64-aec0-41b5-9a5f-e151687410e0.png)

**Comment by bengm** [comment]
Thanks for spotting that. I think I honestly fat-fingered something, and there was a stray partially-deleted line of code.
